### ISSUE TITLE
Sorry not an issue, a question

### ISSUE THREAD

**Issue by eddaly** [EyalRonel/asana-webhooks-manager#4]
Sorry, I could find a better way of contacting you.

I have a Google Sheet / App Script which is syncing Asana data. I am polling currently and would prefer webhooks. Because Apps Script doesn't allow access to headers I can't complete the handshake. I followed a lead I found and played around with using Firebase 'cloud function' as an intermediary and made some progress but taking too long, particularly because I have only basic javascript and web development experience (going too far from apps script for me). So AWM looks perfect. But other than firing up on node server I have no clue how to begin to integrate with the Apps Script. Any pointers welcome.

**Comment by EyalRonel** [comment]
Hi @eddaly, it's great you're considering AWM.

While you'll need to have a little more in-depth understanding in order to modify and extend AWM. I have included detailed documentation about the interception points in the documentation included in the project.

Start up the app, access it's UI via your browser and navigate into the docs section.

**Comment by eddaly** [comment]
I actually managed to get my integration sorted, this code was a useful reference. I guess a dumb question but what's the browser URL when the server's running?!

**Comment by ghost** [comment]
http://localhost:3000
